const PROJECTS_DATA = {
  "meta": {
    "title": "项目总览 · Project Atlas",
    "description": "All projects developed by yun",
    "updated": "2026-07-07"
  },
  "categories": [
    { "id": "ai-agent", "label": "AI / Agent" },
    { "id": "web-app", "label": "Web 应用" },
    { "id": "game", "label": "游戏 / 交互" },
    { "id": "visualization", "label": "可视化" },
    { "id": "tool", "label": "工具" },
    { "id": "content", "label": "内容整理" }
  ],
  "projects": [
    {
      "id": "web-ai-talk",
      "name": "Web AI Talk",
      "description": "AI多服务聊天平台，通过Playwright控制浏览器接入DeepSeek/Kimi/智谱，支持单聊、群聊接力、自动讨论",
      "date": "2026-06",
      "tags": ["AI", "Playwright", "多模型", "Node.js"],
      "category": "ai-agent",
      "type": "folder",
      "path": "/web-ai-talk",
      "entry": "public/index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "agent-bridge",
      "name": "Agent Bridge",
      "description": "AI智能体桥接，多AI终端群聊室，智能体自动参与话题延伸与讨论",
      "date": "2026-05",
      "tags": ["AI", "多智能体", "群聊", "Node.js"],
      "category": "ai-agent",
      "type": "folder",
      "path": "/agent-bridge",
      "entry": "public/index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "rss-reader",
      "name": "RSS 阅读器",
      "description": "RSS订阅管理工具，支持订阅管理、文章聚合、离线阅读、全文搜索",
      "date": "2026-05",
      "tags": ["RSS", "阅读器", "订阅"],
      "category": "web-app",
      "type": "folder",
      "path": "/rss-reader",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/rss-reader",
      "homepage": "https://yun-ai-base.github.io/rss-reader/"
    },
    {
      "id": "news-portal",
      "name": "新闻门户",
      "description": "多栏目新闻聚合展示门户，分类浏览各类新闻资讯",
      "date": "2026-04",
      "tags": ["新闻", "门户", "聚合"],
      "category": "web-app",
      "type": "folder",
      "path": "/news-portal",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "weibo-clone",
      "name": "微博克隆",
      "description": "微博社交媒体界面复刻，信息流展示与交互",
      "date": "2026-04",
      "tags": ["社交", "微博", "UI复刻"],
      "category": "web-app",
      "type": "folder",
      "path": "/weibo-clone",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "xiaohongshu",
      "name": "小红书风格页",
      "description": "小红书风格内容展示页面，卡片式信息流布局",
      "date": "2026-05",
      "tags": ["小红书", "内容展示", "卡片布局"],
      "category": "web-app",
      "type": "folder",
      "path": "/xiaohongshu",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "gesture-image-controller",
      "name": "手势图像控制器",
      "description": "用手势控制图片浏览，支持缩放、旋转、滑动等交互",
      "date": "2026-05",
      "tags": ["手势", "图像", "交互", "MediaPipe"],
      "category": "game",
      "type": "folder",
      "path": "/gesture-image-controller",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "desktop-cat",
      "name": "桌面宠物猫",
      "description": "桌面上会动的猫，互动桌面宠物，陪伴型小应用",
      "date": "2026-05",
      "tags": ["宠物", "桌面", "互动"],
      "category": "game",
      "type": "folder",
      "path": "/desktop-cat",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "snake-3d",
      "name": "3D 贪吃蛇",
      "description": "立体空间中的3D贪吃蛇游戏，Canvas三维渲染",
      "date": "2026-04",
      "tags": ["3D", "游戏", "Canvas", "贪吃蛇"],
      "category": "game",
      "type": "file",
      "path": "/3d-snake-game.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "oriental-pearl-climb",
      "name": "东方明珠爬塔",
      "description": "爬塔闯关游戏，以东方明珠塔为背景的关卡挑战",
      "date": "2026-04",
      "tags": ["游戏", "闯关", "东方明珠"],
      "category": "game",
      "type": "file",
      "path": "/games/oriental-pearl-climb/index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "fireworks",
      "name": "3D 烟花特效",
      "description": "Canvas粒子系统实现的3D烟花特效，缤纷绚丽的粒子动画",
      "date": "2026-04",
      "tags": ["3D", "粒子", "Canvas", "特效"],
      "category": "game",
      "type": "folder",
      "path": "/fireworks",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "morris-quotes",
      "name": "Morris 语录集",
      "description": "100条认知洞察语录分类可视化展示，交互式浏览与探索",
      "date": "2026-06",
      "tags": ["可视化", "语录", "认知", "交互"],
      "category": "visualization",
      "type": "folder",
      "path": "/morris-quotes",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/morris-quotes",
      "homepage": "https://yun-ai-base.github.io/morris-quotes/"
    },
    {
      "id": "learn-io-dashboard",
      "name": "学习仪表盘",
      "description": "学习进度追踪仪表盘，可视化展示学习数据与统计分析",
      "date": "2026-04",
      "tags": ["学习", "仪表盘", "数据可视化"],
      "category": "visualization",
      "type": "folder",
      "path": "/learn-io-dashboard",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "cosmic-first-principles",
      "name": "第一性原理看宇宙",
      "description": "从真空涨落到耗散系统 — 宇宙科普可视化交互页面",
      "date": "2026-05",
      "tags": ["宇宙", "科普", "可视化", "第一性原理"],
      "category": "visualization",
      "type": "file",
      "path": "/cosmic-first-principles.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "cognitive-biases",
      "name": "认知偏见图谱",
      "description": "21种认知偏见可视化图谱，交互式星图探索认知偏差",
      "date": "2026-06",
      "tags": ["可视化", "心理学", "认知", "交互"],
      "category": "visualization",
      "type": "file",
      "path": "/代码文件/21-cognitive-biases-atlas.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "heisenberg-mindmap",
      "name": "物理学与哲学思维导图",
      "description": "海森伯《物理学与哲学》思维导图，物理哲学知识可视化",
      "date": "2026-04",
      "tags": ["思维导图", "物理学", "哲学", "海森伯"],
      "category": "visualization",
      "type": "file",
      "path": "/物理学和哲学_海森伯_思维导图.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "bookmarks",
      "name": "书签导航",
      "description": "个人收藏站点统一管理导航页，分类整理常用链接",
      "date": "2026-06",
      "tags": ["书签", "导航", "收藏"],
      "category": "tool",
      "type": "folder",
      "path": "/bookmarks",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/bookmarks",
      "homepage": "https://yun-ai-base.github.io/bookmarks/"
    },
    {
      "id": "collection",
      "name": "收藏管理系统",
      "description": "带密码验证的文章收藏管理系统，支持分类、搜索、GitHub同步",
      "date": "2026-06",
      "tags": ["收藏", "管理", "密码", "GitHub"],
      "category": "tool",
      "type": "folder",
      "path": "/collection",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/collection",
      "homepage": "https://yun-ai-base.github.io/collection/"
    },
    {
      "id": "binance-futures-bot",
      "name": "币安合约交易机器人",
      "description": "币安合约自动化交易机器人，支持策略回测与实盘交易",
      "date": "2026-06",
      "tags": ["交易", "币安", "机器人", "策略"],
      "category": "tool",
      "type": "folder",
      "path": "/binance-futures-bot",
      "entry": "dashboard.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "x-follow-nav",
      "name": "X 关注分类导航",
      "description": "Twitter(X)关注用户分类管理导航，高效浏览时间线",
      "date": "2026-06",
      "tags": ["Twitter", "X", "导航", "分类"],
      "category": "tool",
      "type": "file",
      "path": "/X关注分类导航.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "demo-audio-player",
      "name": "音频播放器",
      "description": "自定义音频播放器Demo，支持播放控制与可视化效果",
      "date": "2026-04",
      "tags": ["音频", "播放器", "Demo"],
      "category": "tool",
      "type": "file",
      "path": "/demo_audio_player.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "research-frontiers",
      "name": "科研前沿动态",
      "description": "科研前沿动态追踪系统，GitHub Actions自动更新最新科研突破",
      "date": "2026-06",
      "tags": ["科研", "前沿", "自动更新", "GitHub Actions"],
      "category": "content",
      "type": "folder",
      "path": "/research-frontiers",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/research-frontiers",
      "homepage": "https://yun-ai-base.github.io/research-frontiers/"
    },
    {
      "id": "news",
      "name": "新闻热点",
      "description": "每日新闻热点整理页面，精选当日重要资讯",
      "date": "2026-04",
      "tags": ["新闻", "热点", "资讯"],
      "category": "content",
      "type": "folder",
      "path": "/news",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "towards-death",
      "name": "向死而生",
      "description": "AI哲学对话记录可视化 — 海德格尔「向死而生」概念的AI深度对话",
      "date": "2026-05",
      "tags": ["哲学", "AI对话", "海德格尔"],
      "category": "content",
      "type": "folder",
      "path": "/向死而生",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/being-towards-death",
      "homepage": "https://yun-ai-base.github.io/being-towards-death/"
    },
    {
      "id": "vpn-guide-2026",
      "name": "VPN 选购指南 2026",
      "description": "2026年VPN服务选购对比指南，功能对比与推荐排行",
      "date": "2026-06",
      "tags": ["VPN", "指南", "对比"],
      "category": "content",
      "type": "file",
      "path": "/VPN选购指南2026.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "zhihu-change-self",
      "name": "改变自己 — 知乎回答精选",
      "description": "知乎精选回答整理 — 关于自我改变与成长的高赞内容精选",
      "date": "2026-06",
      "tags": ["知乎", "精选", "自我提升"],
      "category": "content",
      "type": "file",
      "path": "/改变自己-知乎回答精选.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "zhihu-enlightenment",
      "name": "悟通的道理 — 知乎回答精选",
      "description": "知乎精选回答整理 — 人生道理与智慧感悟的高赞内容精选",
      "date": "2026-06",
      "tags": ["知乎", "精选", "人生智慧"],
      "category": "content",
      "type": "file",
      "path": "/悟通的道理-知乎回答精选.html",
      "github": "https://github.com/yun-ai-base/ai-chat-room"
    },
    {
      "id": "video-downloader",
      "name": "视频下载器",
      "description": "多平台视频/图片下载工具，支持抖音/快手/小红书解析下载，图片批量勾选，Node.js + Puppeteer",
      "date": "2026-07",
      "tags": ["下载", "抖音", "小红书", "Node.js", "Puppeteer"],
      "category": "tool",
      "type": "folder",
      "path": "/video-downloader",
      "entry": "server.js",
      "github": "https://github.com/yun-ai-base/video-downloader"
    },
    {
      "id": "sciomap",
      "name": "科学星图",
      "description": "121位科学家思想与贡献可视化，D3.js力导向图，支持学科筛选、详情面板含代表作/现代影响/时间线/同时代人/师承树",
      "date": "2026-07",
      "tags": ["可视化", "科学", "D3.js", "知识图谱"],
      "category": "visualization",
      "type": "folder",
      "path": "/sciomap",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/sciomap",
      "homepage": "https://yun-ai-base.github.io/sciomap/"
    },
    {
      "id": "philomap",
      "name": "脉络 Philomap",
      "description": "人类思想星图 — 哲学家可视化探索，支持思想星图/时光长河/哲学光谱/对决/基因测试/孪生宇宙多视图",
      "date": "2026-07",
      "tags": ["可视化", "哲学", "D3.js", "知识图谱"],
      "category": "visualization",
      "type": "folder",
      "path": "/philomap",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/philomap",
      "homepage": "https://yun-ai-base.github.io/philomap/"
    },
    {
      "id": "tool-collection",
      "name": "工具收藏集",
      "description": "个人工具收藏管理页面，分类展示各类实用工具（下载/AI/成人娱乐/信息获取/网络工具/变现赚钱），含点评和相关推荐",
      "date": "2026-07",
      "tags": ["收藏", "工具", "导航", "分类"],
      "category": "tool",
      "type": "folder",
      "path": "/tool-collection",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/tool-collection",
      "homepage": "https://yun-ai-base.github.io/tool-collection/"
    },
    {
      "id": "cosmic-discussion",
      "name": "宇宙大爆炸 AI 对话",
      "description": "AI终端深度对话 — 宇宙大爆炸主题，AI 驱动的交互式科普与哲学讨论",
      "date": "2026-07",
      "tags": ["AI对话", "宇宙", "科普", "终端"],
      "category": "ai-agent",
      "type": "folder",
      "path": "/代码文件/cosmic-discussion",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/cosmic-discussion",
      "homepage": "https://yun-ai-base.github.io/cosmic-discussion/"
    },
    {
      "id": "population-report",
      "name": "中国人口变局综合分析报告",
      "description": "中国人口变局多维数据综合分析报告，覆盖人口结构/婚姻家庭/经济产业/教育/房地产/中日韩比较，含15个交互图表及教育培训行业转型专题",
      "date": "2026-07",
      "tags": ["人口", "数据可视化", "分析报告", "Chart.js"],
      "category": "visualization",
      "type": "folder",
      "path": "/population-report",
      "entry": "index.html",
      "github": "https://github.com/yun-ai-base/population-report",
      "homepage": "https://yun-ai-base.github.io/population-report/"
    }
  ]
};

